# Generated by Django 4.0.6 on 2022-08-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='apellido',
            field=models.CharField(default='juan', max_length=60),
        ),
        migrations.AddField(
            model_name='factura',
            name='ciudad',
            field=models.CharField(default='juan', max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='correo',
            field=models.EmailField(default='juan@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='factura',
            name='direccion',
            field=models.CharField(default='juan', max_length=40),
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre',
            field=models.CharField(default='juan', max_length=60),
        ),
        migrations.AddField(
            model_name='factura',
            name='telefono',
            field=models.CharField(default='juan', max_length=20),
        ),
    ]
